# Generated by Django 5.2 on 2025-05-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('TECIDOS', 'Tecidos'), ('SUBLIMAÇÃO', 'Sublimação'), ('TRANSFER', 'Transfer'), ('OUTROS', 'Outros')], default='OUTROS', max_length=310, verbose_name='Categoria'),
        ),
    ]
