# Generated by Django 5.2 on 2025-04-21 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinValueValidator(14)], verbose_name='CNPJ'),
        ),
    ]
