# Generated by Django 5.2 on 2025-04-21 20:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_fornecedor_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='categoria',
            field=models.CharField(choices=[('SUBLIMACAO E TRANSFER', 'Sublimação e Transfer'), ('SUBLIMACAO', 'Sublimação'), ('TRANSFER', 'Transfer'), ('TECIDOS', 'Tecidos'), ('TODOS', 'Todos')], max_length=25, verbose_name='Categoria de Produtos'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('C', 'Criação'), ('E', 'Edição'), ('D', 'Exclusão'), ('I', 'Importação')], max_length=1)),
                ('modelo_afetado', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField()),
                ('detalhes', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividades',
                'ordering': ['-data_hora'],
            },
        ),
    ]
