# Generated by Django 5.2 on 2025-05-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_fornecedor_categoria_alter_fornecedor_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_normalizado',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
