# Generated by Django 5.2 on 2025-05-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_nome_normalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima',
            field=models.IntegerField(default=5, help_text='Quantidade abaixo da qual o produto deve ser alertado', verbose_name='Quantidade Mínima'),
        ),
    ]
