# Generated by Django 5.2 on 2025-05-06 21:18

from django.db import migrations


def popular_precos(apps, schema_editor):
    Movimentacao = apps.get_model('estoque', 'Movimentacao')
    for mov in Movimentacao.objects.all():
        if not mov.preco_unitario:
            mov.preco_unitario = 0.00
            mov.save()


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produto_options_produto_quantidade_minima'),
    ]

    operations = [
        migrations.RunPython(popular_precos),
    ]
