# Generated by Django 5.2 on 2025-05-06 21:19

# estoque/migrations/0007_movimentacao_fornecedor_movimentacao_preco_unitario.py

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):
    dependencies = [
        ('estoque', '0006_pre_0006_data_fix'),  # Nova dependência
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='fornecedor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='estoque.fornecedor',
                default=None
            ),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='preco_unitario',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                default=Decimal('0.00')  # Default como Decimal
            ),
        ),
    ]
