services:
  - type: web
    name: seu-app-estoque
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn seu_projeto.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: estoque-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DISABLE_COLLECTSTATIC
        value: 0